use crate::decomp_macro::decomp_fn;

decomp_fn!(addmul_decomp3x3, 3, |a_blks, b_blks, c_blks, tmp_mk, tmp_mn, tmp_kn, algos| {
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[2][0]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[1][0]);
    tmp_kn.add_unchecked(&b_blks[2][0]);
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][0].add_unchecked(&tmp_mn);
    c_blks[0][2].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[0][2]);
    tmp_mk.add_unchecked(&a_blks[2][0]);
    tmp_mk.add_unchecked(&a_blks[2][2]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[2][0]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[2][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[0][1]);
    tmp_mk.add_unchecked(&a_blks[2][0]);
    tmp_mk.add_unchecked(&a_blks[2][1]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[1][0]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[2][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[0][2]);
    tmp_mk.add_unchecked(&a_blks[2][0]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[0][2]);
    tmp_kn.add_unchecked(&b_blks[1][0]);
    tmp_kn.add_unchecked(&b_blks[2][0]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][0].add_unchecked(&tmp_mn);
    c_blks[0][2].add_unchecked(&tmp_mn);
    c_blks[2][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][1], &a_blks[0][2]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[1][0]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][0].add_unchecked(&tmp_mn);
    c_blks[1][0].add_unchecked(&tmp_mn);
    c_blks[2][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][1], &a_blks[0][2]);
    tmp_mk.add_unchecked(&a_blks[1][1]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[0][2]);
    tmp_kn.add_unchecked(&b_blks[1][0]);
    tmp_kn.add_unchecked(&b_blks[2][0]);
    tmp_kn.add_unchecked(&b_blks[2][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][2].add_unchecked(&tmp_mn);
    c_blks[1][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][1], &a_blks[0][2]);
    tmp_mk.add_unchecked(&a_blks[1][1]);
    tmp_mk.add_unchecked(&a_blks[1][2]);
    tmp_kn.set_to_sum_unchecked(&b_blks[2][0], &b_blks[2][1]);
    tmp_kn.add_unchecked(&b_blks[2][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[1][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[0][2]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[0][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][0].add_unchecked(&tmp_mn);
    c_blks[0][1].add_unchecked(&tmp_mn);
    c_blks[2][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][1], &a_blks[0][2]);
    tmp_mk.add_unchecked(&a_blks[1][0]);
    tmp_mk.add_unchecked(&a_blks[1][1]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[0][2]);
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    c_blks[1][0].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[0][1]);
    tmp_mk.add_unchecked(&a_blks[1][0]);
    tmp_mk.add_unchecked(&a_blks[1][1]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[0][2]);
    tmp_kn.add_unchecked(&b_blks[1][1]);
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[1][0], &a_blks[1][2]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[1][0].add_unchecked(&tmp_mn);
    c_blks[1][1].add_unchecked(&tmp_mn);
    c_blks[2][1].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][0], &a_blks[1][0]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][1], &b_blks[1][1]);
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    tmp_mk.clear();
    tmp_mk.add_unchecked(&a_blks[1][2]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[2][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[1][0].add_unchecked(&tmp_mn);
    c_blks[1][2].add_unchecked(&tmp_mn);
    c_blks[2][2].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[1][2], &a_blks[2][2]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][1], &b_blks[1][1]);
    tmp_kn.add_unchecked(&b_blks[1][2]);
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_kn.add_unchecked(&b_blks[2][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[2][2].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[1][2], &a_blks[2][1]);
    tmp_mk.add_unchecked(&a_blks[2][2]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][1], &b_blks[1][1]);
    tmp_kn.add_unchecked(&b_blks[1][2]);
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    c_blks[1][1].add_unchecked(&tmp_mn);
    c_blks[2][2].add_unchecked(&tmp_mn);
    tmp_mk.clear();
    tmp_mk.add_unchecked(&a_blks[1][0]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[0][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[1][0].add_unchecked(&tmp_mn);
    c_blks[1][2].add_unchecked(&tmp_mn);
    tmp_mk.clear();
    tmp_mk.add_unchecked(&a_blks[2][1]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][1], &b_blks[1][1]);
    tmp_kn.add_unchecked(&b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[2][1].add_unchecked(&tmp_mn);
    c_blks[2][2].add_unchecked(&tmp_mn);
    tmp_mk.clear();
    tmp_mk.add_unchecked(&a_blks[1][1]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[1][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    c_blks[0][2].add_unchecked(&tmp_mn);
    c_blks[1][1].add_unchecked(&tmp_mn);
    c_blks[1][2].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[1][0], &a_blks[1][2]);
    tmp_mk.add_unchecked(&a_blks[2][0]);
    tmp_mk.add_unchecked(&a_blks[2][2]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[0][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[2][1].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[1][1], &a_blks[1][2]);
    tmp_mk.add_unchecked(&a_blks[2][1]);
    tmp_mk.add_unchecked(&a_blks[2][2]);
    tmp_kn.set_to_sum_unchecked(&b_blks[1][1], &b_blks[1][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    c_blks[1][1].add_unchecked(&tmp_mn);
    tmp_mk.clear();
    tmp_mk.add_unchecked(&a_blks[2][0]);
    tmp_kn.clear();
    tmp_kn.add_unchecked(&b_blks[0][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][0].add_unchecked(&tmp_mn);
    c_blks[0][2].add_unchecked(&tmp_mn);
    c_blks[2][0].add_unchecked(&tmp_mn);
    c_blks[2][2].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[1][0], &a_blks[1][2]);
    tmp_mk.add_unchecked(&a_blks[2][1]);
    tmp_mk.add_unchecked(&a_blks[2][2]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][1], &b_blks[2][1]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][1].add_unchecked(&tmp_mn);
    c_blks[1][1].add_unchecked(&tmp_mn);
    c_blks[2][1].add_unchecked(&tmp_mn);
    tmp_mk.set_to_sum_unchecked(&a_blks[0][1], &a_blks[1][1]);
    tmp_kn.set_to_sum_unchecked(&b_blks[0][0], &b_blks[0][2]);
    tmp_kn.add_unchecked(&b_blks[1][0]);
    tmp_kn.add_unchecked(&b_blks[1][2]);
    tmp_kn.add_unchecked(&b_blks[2][0]);
    tmp_kn.add_unchecked(&b_blks[2][2]);
    tmp_mn.clear();
    addmul_recurse(&mut tmp_mn, &tmp_mk, &tmp_kn, &algos);
    c_blks[0][2].add_unchecked(&tmp_mn);
});